### ISSUE TITLE
支持预加载的方式吗？

### ISSUE THREAD

**Issue by lijie815917** [YvesCheung/SVGAGlidePlugin#10]
有一张帧数比较多的svga，播放时长大概17s。正常加载需要等待大概10s才会播放，采用预加载直接ANR了

**Comment by YvesCheung** [comment]
Glide.with(context).load("xxxx.svga").preload()

**Comment by lijie815917** [comment]
> Glide.with(context).load("xxxx.svga").preload()

不行，直接ANR了

**Comment by YvesCheung** [comment]
看看堆栈是不是OOM崩溃了。如果ANR的话用CPU Profiler看看是阻塞在哪个方法

**Comment by lijie815917** [comment]
> 看看堆栈是不是OOM崩溃了。如果ANR的话用CPU Profiler看看是阻塞在哪个

应该是我的图片太复杂了，第一次解析很慢。我们复杂一点的礼物动画第一次要10秒才能加载出来
