### ISSUE TITLE
升级最新Glide 4.13.2后，这个库导致gif不能播放了

### ISSUE THREAD

**Issue by Archie1068** [YvesCheung/SVGAGlidePlugin#12]

**Comment by YvesCheung** [comment]
我升一下试试

**Comment by YvesCheung** [comment]
e3d93e071c768d1a1d6824abedb4c4f2f3fa7145
我这边也升到4.13.2，但播放gif没有任何问题。用我的demo看看区别在哪里？

**Comment by HolinB** [comment]
确实导致gif不能用了

**Comment by YvesCheung** [comment]
> 确实导致gif不能用了

跟demo的有什么不同的地方？？？？

**Comment by HolinB** [comment]
请求的网络的gif，我把库下载下来并且把glide改回之前的版本就可播放gif了

**Comment by YvesCheung** [comment]
[MainActivity#loadFromNetwork](https://github.com/YvesCheung/SVGAGlidePlugin/blob/master/app/src/main/java/com/yy/mobile/svga/glideplugin/demo/MainActivity.kt) 也是加载网络gif，也能成功。
Glide用4.13.2，然后注释掉svga这个库，可以播放gif吗？

**Comment by HolinB** [comment]
可以的

**Comment by YvesCheung** [comment]
试试
implementation 'com.github.YvesCheung:SVGAGlidePlugin:4.13.2'
