### ISSUE TITLE
大佬带声音的特效，无法播放声音吗

### ISSUE THREAD

**Issue by weipeng321** [YvesCheung/SVGAGlidePlugin#13]

**Comment by YvesCheung** [comment]
最终播放部分还是用 [SVGAPlayer](https://github.com/svga/SVGAPlayer-Android) 播的，声音可以去这个github里问问。
这个库只管资源下载和缓存的部分。

**Comment by weipeng321** [comment]
> 最终播放部分还是用 [SVGAPlayer](https://github.com/svga/SVGAPlayer-Android) 播的，声音可以去这个github里问问。 这个库只管资源下载和缓存的部分。

我使用SVGAPlayer可以播放声音，`  Glide.with(this)
        .load("https://github.com/yyued/SVGA-Samples/blob/master/kingset.svga?raw=true")
        .into(iv_img)`这样加载的话没有声音，但是内存确实非常稳，直接使用SVGAPlayer内存会爆掉

**Comment by YvesCheung** [comment]
我待会看看

**Comment by YvesCheung** [comment]
https://github.com/yyued/SVGA-Samples/blob/master/kingset.svga?raw=true
这个我看出来的videoItem里面也没有声音。
有声音的svga是这个吗？还是其他的？可以播放的SVGAPlayer版本是多少？

**Comment by YvesCheung** [comment]
找了个jojo_audio.svga 确实声音有问题

**Comment by YvesCheung** [comment]
Fix! release 4.13.1

**Comment by weipeng321** [comment]
感谢大佬
