### ISSUE TITLE
SVGAEntityStreamDecoder.inflate fd泄漏

### ISSUE THREAD

**Issue by MazohMa** [YvesCheung/SVGAGlidePlugin#14]
宇哥，我是YY这边的老同事，这边io fd工具检测到SVGAEntityStreamDecoder.inflate 存在句柄泄漏，阔以确认一下不

**Comment by YvesCheung** [comment]
有没有具体的堆栈？

**Comment by YvesCheung** [comment]
泄漏检测原理是动态的hook，还是静态的代码扫描？
如果是静态代码扫描，那么大概率是检测工具的误报，因为inputStream是由Glide内部管理的，我这边不允许close。
See https://github.com/YvesCheung/SVGAGlidePlugin/commit/a66453acd94dc77887f9ff0db526be593fc1f919

**Comment by YvesCheung** [comment]
<img width="704" alt="image" src="https://github.com/YvesCheung/SVGAGlidePlugin/assets/18024705/9ec6f424-d3a2-46d9-bb6b-76cbe08fb7e8">

**Comment by MazohMa** [comment]
> 泄漏检测原理是动态的hook，还是静态的代码扫描？ 如果是静态代码扫描，那么大概率是检测工具的误报，因为inputStream是由Glide内部管理的，我这边不允许close。 See [a66453a](https://github.com/YvesCheung/SVGAGlidePlugin/commit/a66453acd94dc77887f9ff0db526be593fc1f919)

动态检测的，具体原因可以参考这篇文章：https://blog.csdn.net/maniuT/article/details/130131544


不太理解这里为何不主动close.

**Comment by MazohMa** [comment]
> 有没有具体的堆栈？
具体堆栈如下：
dalvik.system.CloseGuard.open(CloseGuard.java:230)
java.util.zip.Inflater.<init>(Inflater.java:122)
java.util.zip.Inflater.<init>(Inflater.java:129)
java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:126)
com.opensource.svgaplayer.glideplugin.SVGAEntityStreamDecoder.inflate(Unknown Source:14)
com.opensource.svgaplayer.glideplugin.SVGAEntityStreamDecoder.decode(Unknown Source:0)
com.opensource.svgaplayer.glideplugin.SVGAEntityStreamDecoder.decode(Unknown Source:2)
com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(Unknown Source:32)
com.bumptech.glide.load.engine.DecodePath.decodeResource(Unknown Source:18)
com.bumptech.glide.load.engine.DecodePath.decode(Unknown Source:0)
com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(Unknown Source:31)
com.bumptech.glide.load.engine.LoadPath.load(Unknown Source:19)
com.bumptech.glide.load.engine.DecodeJob.runLoadPath(Unknown Source:25)
com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(Unknown Source:10)
com.bumptech.glide.load.engine.DecodeJob.decodeFromData(Unknown Source:11)
com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(Unknown Source:62)
com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(Unknown Source:33)
com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(Unknown Source:13)
com.bumptech.glide.load.model.FileLoader$FileFetcher.loadData(Unknown Source:10)
com.bumptech.glide.load.engine.DataCacheGenerator.startNext(Unknown Source:94)
com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(Unknown Source:88)
com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(Unknown Source:33)
com.bumptech.glide.load.engine.DataCacheGenerator.onDataReady(Unknown Source:13)
com.bumptech.glide.load.model.ByteBufferFileLoader$ByteBufferFetcher.loadData(Unknown Source:6)
com.bumptech.glide.load.engine.DataCacheGenerator.startNext(Unknown Source:94)
com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:62)
com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:27)

**Comment by YvesCheung** [comment]
感谢你提供的原理和堆栈，问题就很清晰而且可以解决。
fix：
e3b6fda7c7d7708766d0133bc590094e01f18d5c

**Comment by YvesCheung** [comment]
1. 这里不能直接使用inputStream.close。
    因为这个资源是由Glide来管理的。比如同一个文件流，Glide会尝试用不同的Decoder来解码，比如先尝试用Gif的，发现不对，再用PNG的。如果Gif解码器把流关掉了，那么PNG解码器就必然会失败，导致图片最终无法正常展示。所以流是不能在这里关闭的，要由Glide最终统一去关闭。

2. inputStream没有泄漏，泄漏的是里面的Inflater。
    但是InflateInputStream没有提供只关闭Inflater，但不关闭stream的接口。所以改成自己传Inflater进去，然后结束后手动关闭Inflater。

**Comment by YvesCheung** [comment]
release 4.13.3
