### ISSUE TITLE
Could not find com.github.YvesCheung:SVGAGlidePlugin

### ISSUE THREAD

**Issue by benedictcontawe** [YvesCheung/SVGAGlidePlugin#15]
Configuration cache state could not be cached: field `compileTimeDependencies` of task `:app:dataBindingMergeDependencyArtifactsDebug` of type `com.android.build.gradle.internal.tasks.databinding.DataBindingMergeDependencyArtifactsTask`: error writing value of type 'org.gradle.api.internal.artifacts.configurations.ResolutionBackedFileCollection'
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not find com.github.YvesCheung:SVGAGlidePlugin:4.15.2.
     Required by:
         project :app

**Comment by YvesCheung** [comment]
The latest version is `4.13.3`

**Comment by YvesCheung** [comment]
How did 4.15.2 come about?

**Comment by benedictcontawe** [comment]
Thanks version updated error fixed thanks
