### ISSUE TITLE
怎么控制glide只播放一次svga呢?

### ISSUE THREAD

**Issue by clbDream** [YvesCheung/SVGAGlidePlugin#8]

**Comment by clbDream** [comment]
或者有什么方法判断播放完成

**Comment by YvesCheung** [comment]
Glide只负维护资源，SVGAPlayer播放多少次跟Glide没关系。
看SVGAPlayer源码startAnimation：
```java
animator.setRepeatCount(this.loops <= 0 ? 99999 : this.loops - 1);
```
可以知道loops默认是99999次，可以设成1就是只播1次。
修改方式：
```kotlin
iv_img.loops = 1
Glide.with(this).load(url).into(iv_img)
```
也可以重写`SVGATarget`不调用startAnimation：
```kotlin
Glide.with(this).load(url).into(object : DrawableImageViewTarget(iv_img) {
      override fun setResource(resource: Drawable?) {
          if (resource is SVGADrawable) {
              iv_img.setVideoItem(resource.videoItem, resource.dynamicItem)
              //iv_img.startAnimation()
          } else {
              super.setResource(resource)
          }
      }
  })
```
因为注释了`startAnimation`所以一次都不会播。

**Comment by clbDream** [comment]
还有一个问题就是有些svga最后一帧不是透明的,之前是播放完成后清楚了一下画布,现在用这个库的话,有什么办法处理吗

**Comment by YvesCheung** [comment]
清除了一下画布是指重写SVGAImageView的onDraw吗？同样的做法不就好了？
这个库只是做下载资源。之前的其他处理应该不影响阿？

**Comment by YvesCheung** [comment]
播放结束后把SVGAImageView设一个透明颜色的Drawable？

**Comment by YvesCheung** [comment]
播放结束后把SVGAImageView设setVisibility(INVISIBLE) ?

**Comment by clbDream** [comment]
就是之前是通过这个来播放svga的,可以通过里面的回调来监听svga是否播放完成,可以做其他的相关操作
![image](https://user-images.githubusercontent.com/28987014/157566822-ec2e4a99-c229-4c00-8f0f-debdd4f28a36.png)
 现在如果改成Glide加载的话,该如何监听他的播放完成呢?

**Comment by YvesCheung** [comment]
刚刚去看了一下decodeFromURL的源码，只是一个把资源转化成SVGAVideoEntity的过程而已，ParseCompletion回调是资源解析完成或者失败的回调。另外PlayCallback也是在播放前回调，告诉外面解析出来的File列表。
svga播放完成具体是指SVGAParser的哪个回调？

**Comment by YvesCheung** [comment]
你要的播放完成的回调应该是在`SVGAImageView`的`SVGACallback.onFinished()`。跟SVGAParser没有关系。

**Comment by clbDream** [comment]
好的,我这边按照这种方法处理好了,多谢
